### PR TITLE
Card selection

### PR DESCRIPTION
**Pull request by naim16031988**
i fixed the spacing between the card on mobile view . please cheek it out and let me know if the is any thing to update 
thank you 

https://roaring-taiyaki-8c7335.netlify.app/

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Hey @Naim 
You're simply awesome. I love your PR. Before merging please resolve conflicts

**Comment by naim** [comment]
Just a heads up that you keep tagging me incorrectly.

**Comment by naim16031988** [comment]
I just resolve the conflicts .

**Comment by MohamedMafaz** [comment]
I wanted to take a moment to express my heartfelt gratitude for your remarkable contribution. Your dedication, expertise, and unwavering commitment have made a significant impact on our project. Your positive attitude and willingness to support others have created a welcoming environment, and your exceptional work ethic has set a benchmark for excellence. Thank you for your invaluable contributions; we are truly fortunate to have you on our team.

**Pull request merged**
