### PR TITLE
pages responsiveness

### PR DESCRIPTION
**Pull request by naim16031988**
I added the meta name viewport to get a resposive screen

### CODE REVIEW

**Comment by naim16031988** [comment]
this is the link
https://unique-crostata-e6b747.netlify.app/

**Comment by MohamedMafaz** [comment]
Hey @naim16031988 
I saw your live preview & it's simply awesome. I can't wait to merge it. But, it has some conflicts. So, please resolve them

**Comment by naim16031988** [comment]
i dont know why i can't resolve this right here 
Screenshot 2023-06-04 074035

**Comment by MohamedMafaz** [comment]
Are you tried using code editor?

**Comment by naim16031988** [comment]
I am always fixing conflict with the editor . This one it says it is more complex so i need to use visual studio . I will figure out a way to do it

**Comment by naim16031988** [comment]
sorry bro, i dont know how to do it

**Comment by MohamedMafaz** [comment]
Hey @naim16031988 
I tried to resolve it myself. But, I can't able to do it. Now, I understood how to do it. At first you need to install Github Desktop. And clone my repo into your machine. In Github Desktop you can see what are the lines are conflicting. You need to copy & paste it in code editor which have cloned repo by me. After completing these, the conflicts are resolved.

Thanks & Regards,
Mohamed Mafaz P R,
Propoplex.

**Comment by naim16031988** [comment]
Ok thanks. I will try that

**Comment by naim16031988** [comment]
i cant do that sorry about it

**Pull request closed without merging**
