### PR TITLE
Card selection 

### PR DESCRIPTION
**Pull request by naim16031988**
check if this is the way you want do it 
let me know if there is any issue 
thank you

### CODE REVIEW

**Comment by naim16031988** [comment]
https://roaring-taiyaki-8c7335.netlify.app/

**Comment by MohamedMafaz** [comment]
Hey @Naim,

I hope this message finds you well. I wanted to take a moment to express my admiration for your outstanding contribution to the website. Your hard work and dedication truly shine through, and I want to extend my heartfelt appreciation for all that you've done.

However, while browsing the website on my mobile device, I noticed a minor issue that I wanted to bring to your attention. There seems to be a small space between the selected card and the following card, which slightly affects the overall user experience. I believe addressing this issue will further enhance the site's usability and visual appeal.

I understand that perfection is a continuous journey, and bugs and glitches are bound to occur. Hence, I thought it would be helpful to share this feedback with you, as I believe it can contribute to improving the mobile browsing experience for all users.

Once again, thank you for your exceptional work on the website. Your efforts have not gone unnoticed, and I greatly value your contributions to the project. If you need any assistance or further details regarding the mobile spacing issue, please don't hesitate to reach out.

Wishing you continued success!

Warm regards,
Mohamed Mafaz P R,
Propoplex.

**Comment by naim16031988** [comment]
OK,thanks for you feedback .i will fixe this

**Comment by naim16031988** [comment]
Hi,
I diged into the CSS file and I think I fixed the issue. can you please check and let me know if there is anything else to change? 
thank you.

https://roaring-taiyaki-8c7335.netlify.app/

**Comment by naim16031988** [comment]
I closed this pull request to request another one

**Pull request closed without merging**
