### PR TITLE
button

### PR DESCRIPTION
**Pull request by naim16031988**
this is a solution to the button hover please check it out

### CODE REVIEW

**Comment by naim16031988** [comment]
https://resplendent-platypus-cbfe6f.netlify.app/

**Comment by MohamedMafaz** [comment]
Hey @naim16031988 
You're simply awesome bro!

**Comment by MohamedMafaz** [comment]
Hi bro!
Is there any possibility to make link active when user visits mohamedmafaz.github.io/Propoplex  I found a bug that after clicking the page If I click anything else, that gray colour disappears.

**Comment by MohamedMafaz** [comment]
Uploading Propoplex_ Your Freelancing Partner.mp4…

**Comment by MohamedMafaz** [comment]
Take a look at this

https://github.com/MohamedMafaz/Propoplex/assets/113255500/d7f2f003-7fb4-46b5-a158-b50df0020a60

**Comment by naim16031988** [comment]
Alright i will give it a try

**Comment by naim16031988** [comment]
i just pulled request this issue.

**Pull request merged**
