### PR TITLE
pages responsivness

### PR DESCRIPTION
**Pull request by naim16031988**
i modified a lot of lines of code to get this result. i know we should have a discussion about it. thank you for checking my work. 
let me know what to change 
thanks

### CODE REVIEW

**Comment by naim16031988** [comment]
https://unique-crostata-e6b747.netlify.app/

**Comment by MohamedMafaz** [comment]
I'll check it

**Comment by MohamedMafaz** [comment]
Hey @naim16031988
I checked out the link you given. I saw that About, Login, Request New Tool pages aren't look responsive. Even the navbar also not collapsed. Can you please check it out?

**Comment by MohamedMafaz** [comment]
If you think it consume lot of hours & you're feeling bad on editing the code. Just let me know. I'll merge this PR & Modify it

**Comment by naim16031988** [comment]
Let me try first . If i get trouble i ll let you know

**Comment by naim16031988** [comment]
So this is a video of what i am getting 

https://github.com/MohamedMafaz/Propoplex/assets/125624860/15a2c6d1-924a-46c6-b92e-d19131052703

**Comment by MohamedMafaz** [comment]
This is what I am getting in mobile. Not in developer tools. You may try with the mobile phone
https://github.com/MohamedMafaz/Propoplex/assets/113255500/ff0a7b88-21c1-418e-9c8e-f447e1becdae

**Comment by naim16031988** [comment]
Oh, sorry i was only checking with a developing tools . I thought it is the same as the mobile . I think i know how to fixe that

**Comment by MohamedMafaz** [comment]
I also thought that both are same. I have a mobile on my desk. So, that I checked with it.

**Pull request closed without merging**
