### PR TITLE
Added navbar to contact file

### PR DESCRIPTION
**Pull request by MwendwaDev**
I added a navbar in the contact section and added a margin on the contact container for the navbar.

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Can you provide the live link which is hosted in github pages

**Comment by MwendwaDev** [comment]
https://mwendwadev.github.io/Propoplex.github.io/contactus.html  @MohamedMafaz

**Comment by MohamedMafaz** [comment]
Hey @MwendwaDev 
You need to fix the above bugs to be merged 

- Icons not shown in navbar
- GO PREMIUM Button need to be in single line
- Need to add a favicon
- Remove unwanted image (3 Businessmen with neckties)
- The form need to be more wider

**Comment by MwendwaDev** [comment]
All done, please check it out @MohamedMafaz

**Pull request closed without merging**
